-- Use the customer_behavior database
USE customer_behavior;
GO

--------------------------------------------------------------------------------
-- Q1: Total revenue generated by male vs. female customers
--------------------------------------------------------------------------------
SELECT 
    gender, 
    SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

--------------------------------------------------------------------------------
-- Q2: Customers who used a discount but spent more than the average purchase amount
--------------------------------------------------------------------------------
SELECT 
    customer_id,
    purchase_amount
FROM customer
WHERE discount_applied = 'Yes' 
  AND purchase_amount >= (
      SELECT AVG(purchase_amount) 
      FROM customer
  );

--------------------------------------------------------------------------------
-- Q3: Top 5 products with the highest average review rating
--------------------------------------------------------------------------------
SELECT TOP 5
    item_purchased, 
    ROUND(AVG(review_rating), 2) AS average_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC;

--------------------------------------------------------------------------------
-- Q4: Compare average purchase amounts between Standard and Express shipping
--------------------------------------------------------------------------------
SELECT 
    shipping_type, 
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

--------------------------------------------------------------------------------
-- Q5: Do subscribed customers spend more? Compare average spend and total revenue
--------------------------------------------------------------------------------
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;

--------------------------------------------------------------------------------
-- Q6: Top 5 products with the highest percentage of purchases using discounts
--------------------------------------------------------------------------------
SELECT TOP 5
    item_purchased,
    ROUND(
        SUM(CASE WHEN discount_applied = 'Yes' THEN 1.0 ELSE 0 END) 
        / COUNT(*) * 100, 
        2
    ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC;

--------------------------------------------------------------------------------
-- Q7: Segment customers into New, Returning, and Loyal based on previous purchases
--------------------------------------------------------------------------------
WITH customer_type AS (
    SELECT 
        customer_id, 
        previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT 
    customer_segment, 
    COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;

--------------------------------------------------------------------------------
-- Q8: Top 3 most purchased products within each category
--------------------------------------------------------------------------------
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT 
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;

--------------------------------------------------------------------------------
-- Q9: Are repeat buyers (more than 5 previous purchases) more likely to subscribe?
--------------------------------------------------------------------------------
SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--------------------------------------------------------------------------------
-- Q10: Revenue contribution of each age group
--------------------------------------------------------------------------------
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
